if (NOT LAME_INCLUDE_DIRS OR NOT LAME_LIBRARIES)
	find_path(LAME_INCLUDE_DIRS lame/lame.h)
	find_library(LAME_LIBRARIES NAMES mp3lame)

	if (LAME_INCLUDE_DIRS AND LAME_LIBRARIES)
		set(LAME_FOUND TRUE)
	endif (LAME_INCLUDE_DIRS AND LAME_LIBRARIES)

	if (NOT LAME_FOUND)
		if (LAME_FIND_REQUIRED)
			message(FATAL_ERROR "Could NOT find lame development files")
		endif (LAME_FIND_REQUIRED)
	endif (NOT LAME_FOUND)
endif (NOT LAME_INCLUDE_DIRS OR NOT LAME_LIBRARIES)